#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 
SOURCE_ROOT="../../src" 

# Fortran compiler
F77="ftn"

# C compiler
CC="cc"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
# NEKCOMM, NEKDLAY, BG, MGRID
#PPLIST="?"


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"
#USR_LFLAGS="-L$HOME/mylib/EMPI4Re/lib -lmpi"
#USR_LFLAGS="-L$HOME/mylib/EMPI4Re/lib -I$HOME/mylib/EMPI4Re/include -lmpi"
#-L/path/to/ipm/lib -lipm
#USR_LFLAGS="-L/afs/pdc.kth.se/home/i/ilyai/libs/ipm/lib -lipm -lmpi" 
#USR_LFLAGS="-L/afs/pdc.kth.se/home/i/ilyai/libs/mpip/lib -lmpiP -lbfd"
# generic compiler flags
#G="-h omp"
#G="-L$HOME/mylib/EMPI4Re/lib -I$HOME/mylib/EMPI4Re/include -lmpi"
# show witch O flads uses
#G="-eo"
# optimization flags
#OPT_FLAGS_STD=""
#OPT_FLAGS_MAG=""

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
